name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm clean-install
      - name: Lint
        run: npm run lint
      - name: Check if build works
        run: npm run build
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/git
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.RELEASE_NPM_TOKEN }}
          GIT_AUTHOR_NAME: ${{ vars.RELEASE_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ vars.RELEASE_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ vars.RELEASE_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ vars.RELEASE_AUTHOR_EMAIL }}
        run: semantic-release --branches main --plugins @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/npm @semantic-release/github @semantic-release/git
